add_link_options(-static-libgcc -static-libstdc++ -static)
link_libraries(ole32 oleaut32)

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

# MinGW sysroot 경로 (cmake -DMINGW_ROOT_PATH=... 로 오버라이드 가능)
if(NOT CMAKE_FIND_ROOT_PATH)
    if(APPLE)
        set(CMAKE_FIND_ROOT_PATH /opt/homebrew/opt/mingw-w64)
    else()
        set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
    endif()
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)